name: Build and Deploy

on:
  push:
    branches:
      - main # Если твоя ветка называется иначе, измени её здесь

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v4

      - name: Логин в Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Установка переменной с тегом
        run: echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV

      - name: Сборка и пуш образа
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:${{ env.IMAGE_TAG }} .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:${{ env.IMAGE_TAG }}
