name: Build and Deploy

on:
  push:
    branches:
      - main # Если твоя ветка называется иначе, изменяй на нужную

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v4

      - name: Логин в Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Установка переменной с тегом
        run: echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV

      - name: Сборка и пуш образа
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:${{ env.IMAGE_TAG }} .
          docker push ${{ secrets.DOCKER_HUB_PASSWORD }}/my-app:${{ env.IMAGE_TAG }}

      - name: Подключение к серверу и деплой
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:${{ env.IMAGE_TAG }}
            docker stop my-app || true
            docker rm my-app || true
            docker run -d --name my-app -p 80:3000 ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:${{ env.IMAGE_TAG }}
