name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v4

      - name: Логин в Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Установка переменной с тегом
        run: echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV

      - name: Сборка и пуш образа
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:${{ env.IMAGE_TAG }} .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:${{ env.IMAGE_TAG }}

      - name: Остановка старого контейнера
        run: |
          docker stop my-app || true
          docker rm my-app || true

      - name: Запуск нового контейнера
        run: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:${{ env.IMAGE_TAG }}
          docker run -d --name my-app -p 80:80 ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:${{ env.IMAGE_TAG }}
